version: '3.7'

services:
  redis:
    image: redis:alpine
    container_name: "meetappredis"
    ports:
      - "6379:6379"
  database:
    image: postgres
    container_name: "meetappdb"
    depends_on:
      - "redis"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=meetapp
    ports:
      - "5432:5432"
  backend:
    image: trosdan/meetappbackend:0.1
    container_name: "meetappbackend"
    environment:
      - DB_HOST=172.17.0.1
      - REDIS_HOST=172.17.0.1
    depends_on:
      - "database"
    ports:
      - "3333:3333"
  frontend:
    image: trosdan/meetappfrontend:0.1
    container_name: "meetappfrontend"
    depends_on:
      - "database"
    ports:
      - "3000:3000"
